name: Libsyscall (x86_64, arm64, PLATFORM = MacOSX)

on:
  workflow_dispatch:

  push:
    branches:
      - stable/6153/latest

jobs:
    build:
      runs-on: macos-latest
  
      steps:
        - name: Clone Sources
          run: |
            git clone --branch ${GITHUB_REF_NAME} https://github.com/Zormeister/xnu ~/xnu
            git clone --branch $(cat ~/xnu/depconfig/dtrace) https://github.com/apple-oss-distributions/dtrace.git ~/dtrace
            git clone --branch $(cat ~/xnu/depconfig/AvailabilityVersions) https://github.com/apple-oss-distributions/AvailabilityVersions.git ~/AvailabilityVersions
            git clone --branch $(cat ~/xnu/depconfig/libdispatch) https://github.com/apple-oss-distributions/libdispatch.git ~/libdispatch
            git clone  https://github.com/Zormeister/EmbeddedDeviceMap.git ~/EmbeddedDeviceMap
        - name: Install Homebrew Packages
          run: |
            brew install jsoncpp
        - name: Run Preflight script
          run: |
            cd ~/xnu/
            ${PWD}/ci_preflight.sh
        - name: Install availability.pl
          run: |
            cd ~/AvailabilityVersions
            mkdir -p $(xcrun --sdk macosx -show-sdk-path)/usr/local/libexec
            make DSTROOT=$(xcrun --sdk macosx -show-sdk-path) install_script
        - name: Install EmbeddedDeviceMap
          run: |
            cd ~/EmbeddedDeviceMap
            make DESTDIR=$(xcrun --sdk macosx -show-sdk-platform-path) install
        - name: Install ctfconvert, ctfdump and ctfmerge.
          run: |
            cd ~/dtrace
            echo "#include <stdint.h>" > include/llvm-Support/DataTypes.h
            sed -i -e 's,include "llvm/Support/DataTypes,include "llvm-Support/DataTypes,' include/llvm-Support/PointerLikeTypeTraits.h
            xcodebuild install CODE_SIGNING_ALLOWED=NO DSTROOT=$(xcrun --sdk macosx -show-sdk-platform-path) INSTALL_PATH="/usr/local/bin" -target ctfconvert -target ctfdump -target ctfmerge -sdk macosx
        - name: Install XNU headers
          run: |
            export RC_ProjectName="xnu_headers"
            export RC_ProjectNameAndSourceVersion="xnu_headers-$(cat ~/xnu/sourceversion)"
            export RC_ProjectSourceVersion="$(cat ~/xnu/sourceversion)"
            export RC_ProjectBuildVersion="$(cat ~/xnu/buildversion)"
            export RC_XBS="YES"
            cd ~/xnu/
            make EMBEDDED_DEVICE_MAP=$(xcrun -f embedded_device_map) EDM_DBPATH=$(xcrun --sdk macosx -show-sdk-platform-path)/usr/local/standalone/firmware/device_map.db DO_CTFMERGE=0 USE_WERROR=0 OBJROOT=$PWD DSTROOT=$(xcrun --sdk macosx -show-sdk-path) ARCH_CONFIGS="X86_64" installhdrs
            make EMBEDDED_DEVICE_MAP=$(xcrun -f embedded_device_map) EDM_DBPATH=$(xcrun --sdk macosx -show-sdk-platform-path)/usr/local/standalone/firmware/device_map.db DO_CTFMERGE=0 USE_WERROR=0 OBJROOT=$PWD DSTROOT=$(xcrun --sdk macosx -show-sdk-path) PRODUCT_CONFIGS="rpi3b" installhdrs
        - name: Prepare libfirehose_kernel
          run: |
            cd ~/libdispatch
            mkdir -p $(xcrun --sdk macosx -show-sdk-path)/usr/local/include/os
            cp ~/libdispatch/os/firehose_buffer_private.h $(xcrun --sdk macosx -show-sdk-path)/usr/local/include/os
            awk '/include "<DEVELOPER/ {next;} /SDKROOT =/ {print "SDKROOT = macosx"; next;} {print $0}' xcodeconfig/libdispatch.xcconfig > .__tmp__ && mv -f .__tmp__ xcodeconfig/libdispatch.xcconfig
            xcodebuild install VALID_ARCHS="x86_64 x86_64h arm64 armv7 armv7k" DSTROOT=$(xcrun --sdk macosx -show-sdk-path) -target libfirehose_kernel -arch x86_64
        - name: Build Libsyscall
          run: |
            export RC_ProjectName="Libsyscall"
            export RC_ProjectNameAndSourceVersion="Libsyscall-$(cat ~/xnu/sourceversion)"
            export RC_ProjectSourceVersion="$(cat ~/xnu/sourceversion)"
            export RC_ProjectBuildVersion="$(cat ~/xnu/buildversion)"
            export RC_XBS="YES"
            cd ~/xnu/
            xcodebuild -project libsyscall/Libsyscall.xcproject VALID_ARCHS="x86_64 arm64" DSTROOT="$PWD/LIBSYSCALLROOT" install -arch x86_64 -arch arm64
        - name: Package RELEASEROOT into a tarball
          run: |
            export RC_ProjectName="xnu"
            export RC_ProjectNameAndSourceVersion="xnu-$(cat ~/xnu/sourceversion)"
            export RC_ProjectSourceVersion="$(cat ~/xnu/sourceversion)"
            export RC_ProjectBuildVersion="$(cat ~/xnu/buildversion)"
            export RC_XBS="YES"
            cd ~/xnu/
            cd $PWD/LIBSYSCALLROOT
            tar -cvf "${RC_ProjectNameAndSourceVersion}~${RC_ProjectBuildVersion}.tar.xz" .
            mkdir -p ~/xnu/BUILDS
            cp ./*.tar.xz ~/xnu/BUILDS/
        - name: Upload Libsyscall Tarball
          if: success()
          uses: actions/upload-artifact@v4
          with:
            path: /Users/runner/xnu/BUILDS
